name: AngryPomodoro
options:
  deploymentTarget:
    iOS: 16.0
packages: {}
targets:
  AngryPomodoro:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: App
      - path: Resources
    settings:
      INFOPLIST_FILE: Resources/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets:
        - AngryPomodoroTests
  AngryPomodoroTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: AngryPomodoro
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.angrypomodoro.app
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
